#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Sensor, S2,     gyroSensor,     sensorI2CHiTechnicGyro)
#pragma config(Sensor, S3,     ultraSanic,     sensorSONAR)
#pragma config(Sensor, S4,     irSensor,       sensorI2CCustom)
#pragma config(Motor,  motorA,          nxtHandMtr,    tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     frontLeft,     tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     frontRight,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     backRight,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     backLeft,      tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C3_1,     armBranchTurner, tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     collectorMtr,  tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C4_1,    clampSrvo,            tServoStandard)
#pragma config(Servo,  srvo_S1_C4_2,    ballCoverSrvo,        tServoStandard)
#pragma config(Servo,  srvo_S1_C4_3,    clampSlideSrvo,       tServoContinuousRotation)
#pragma config(Servo,  srvo_S1_C4_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "CascadeLibrary.h"  //Include file to "handle" the Bluetooth messages.

////////////////////////////////////////
//
// This is to grab the small goal (the one in front of the ramp) and deliver it to the parking zone
// The robot will be facing BACKWARD on the RAMP
// ALMOST FINISHED (needs testing)
//
////////////////////////////////////////\

void initializeRobot() //Start
{
	normalize(); //Make stuff normal
  return;
}

void findAndGrabGoals() {

}

task main()
{
  initializeRobot();

  waitForStart(); //Wait for the beginning of autonomous phase.

	goForward(380, 1); //Go forward 3.8 sec backward
	turn(10); //fix to missing goal
	goForward(380, 1);
	clampRotate(1);
	turn(25);
	goForward(850, -1); //Go forward 8.5 sec forward
	turn(60); //Turn 60ish degrees

  while (true)
  {

 	}
}
