#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Sensor, S2,     gyroSensor,     sensorI2CHiTechnicGyro)
#pragma config(Sensor, S4,     irSensor,       sensorI2CCustom)
#pragma config(Motor,  motorA,          nxtHandMtr,    tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     frontLeft,     tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     frontRight,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     backRight,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     backLeft,      tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C3_1,     armBranchTurner, tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     collectorMtr,  tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C4_1,    clampSrvo,            tServoStandard)
#pragma config(Servo,  srvo_S1_C4_2,    ballCoverSrvo,        tServoStandard)
#pragma config(Servo,  srvo_S1_C4_3,    clampSlideSrvo,       tServoContinuousRotation)
#pragma config(Servo,  srvo_S1_C4_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// Defined automatically by ROBOTC

#include "CascadeLibrary.h" //Includes the library, which has the driving functions etc.

/*****************************************MAIN FUNCTIONS**************************************************************************/
void initializeRobot() { //Our own function to initialize the robot for teleop mode
	teleop = true;
}

//Drives the robot's four wheels
task runDrive() {
	while(true) {
		getJoystickSettings(joystick);
		if(joy1Btn(9)){
			emergencyBrake();
		}
		singleStickDrive(joystick.joy1_x2, joystick.joy1_y2);
	}
}

task nonArmSystem () { //controls everything on the robot that isn't on or relating to the arm
	while (true) {
			getJoystickSettings(joystick);
			/*if (joy2Btn(1)) { // Forward usual
				ToggleBallCollecter(1);
			}else if(joy2Btn(2)){ // Stop Completely
				ToggleBallCollecter(2);
			}else if(joy2Btn(3)){ // Go Backward5
				ToggleBallCollecter(3);
			}*/
			//clampSlide(joy1Btn(1)); //this is suppose to move the slider thing
			clampRotate(joy1Btn(2));
			//doorServo(joy2Btn(4));
	}
}

task armSystem () {
	while (true) {
		getJoystickSettings(joystick);
		joyButtonArmMov(joy1btn(7), joy1btn(8));
		if(joy1Btn(5)) {
			doorServo(1);
		} else {
			doorServo(0);
		}
	}
}


task main() {
  initializeRobot();

  waitForStart();

 	StartTask(runDrive);
	StartTask(nonArmSystem);
	StartTask(armSystem);
  while(true){

	}
}
